apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
    - name: 1st
      image: nginx
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
    - name: 2nd
      image: debian
      command: ["/bin/bash", "-c"]
      args: ["while true; do date >> /html/index.html; sleep 1; done"]
      volumeMounts:
        - name: html
          mountPath: /html