apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: demo
    run: demo
spec:
  containers:
    - name: demo-container
      image: gcr.io/k8s-k3s/demo:v1.0.0
      ports:
        - name: http
          containerPort: 8000
      livenessProbe:
        httpGet:
          path: /
          port: http
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /ready
          port: http
        initialDelaySeconds: 0
        periodSeconds: 2
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1